'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import Image from 'next/image';

type Member={companyId:string;companyName:string;industryName:string;prefecture:string;businessDescription:string;offerSummary:string;challengeCount:number};
type Challenge={id:string;companyId:string;companyName:string;industryName:string;prefecture:string;title:string;detail:string;category:string;urgency:string;offerSummary:string};
type Message={id:string;senderCompanyId:string;recipientCompanyId:string;senderAccountId:string;recipientAccountId:string;senderCompanyName:string;recipientCompanyName:string;body:string;createdAt:string};
type Account={id:string;companyId:string;name:string;jobTitle:string;status:string;iconDataUrl:string};
const field='h-10 bg-white border border-slate-300 rounded-lg px-3 text-sm text-[#172033] focus:outline-none focus:ring-2 focus:ring-blue-500';

export default function NetworkPanel(){
 const [members,setMembers]=useState<Member[]>([]),[challenges,setChallenges]=useState<Challenge[]>([]),[messages,setMessages]=useState<Message[]>([]);
 const [account,setAccount]=useState<Account|null>(null),[target,setTarget]=useState(''),[query,setQuery]=useState(''),[draft,setDraft]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
 const myCompany=account?.companyId??'';
 const toast=(v:string)=>{setNotice(v);setTimeout(()=>setNotice(''),3000)};
 const load=useCallback(async(search=query)=>{setLoading(true);try{await fetch('/api/session',{cache:'no-store'});const r=await fetch(`/api/network?query=${encodeURIComponent(search)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error();setMembers(d.members??[]);setChallenges(d.challenges??[]);setMessages(d.messages??[]);setAccount(d.account??null)}catch{toast('企業ネットワークを読み込めませんでした')}finally{setLoading(false)}},[query]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);
 const conversation=useMemo(()=>messages.filter(m=>(m.senderCompanyId===myCompany&&m.recipientCompanyId===target)||(m.senderCompanyId===target&&m.recipientCompanyId===myCompany)),[messages,myCompany,target]);
 const talks=useMemo(()=>members.filter(m=>m.companyId!==myCompany).map(member=>{const latest=[...messages].reverse().find(message=>(message.senderCompanyId===myCompany&&message.recipientCompanyId===member.companyId)||(message.senderCompanyId===member.companyId&&message.recipientCompanyId===myCompany));return{member,latest}}).filter(item=>item.latest).sort((a,b)=>new Date(b.latest!.createdAt).getTime()-new Date(a.latest!.createdAt).getTime()),[members,messages,myCompany]);
 const send=async()=>{if(!target||!draft.trim())return toast('送信先と本文を入力してください');const r=await fetch('/api/network',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:'message',recipientCompanyId:target,body:draft})}),d=await r.json();if(!r.ok)return toast(d.error||'送信できませんでした');setDraft('');await load();toast('登録企業へDMを送信しました')};
 const selectCompany=(id:string)=>{if(id===myCompany)return toast('自社にはDMできません');setTarget(id)};
 const targetMember=members.find(m=>m.companyId===target);
 return <div className="space-y-5 pb-12">
  {notice&&<div className="fixed top-5 right-5 z-50 bg-blue-600 text-white px-4 py-3 rounded-lg shadow-xl text-sm">{notice}</div>}
  <header className="flex flex-col lg:flex-row lg:items-end justify-between gap-3"><div><span className="text-xs font-bold text-blue-600">SALES NAVI NETWORK</span><h2 className="text-2xl font-bold text-[#161c2c] mt-1">企業間課題マッチング・DM</h2><p className="text-sm text-slate-500 mt-1">営業ナビに登録した企業同士で、公開課題を探して提案・相談できます。</p></div><div className="flex items-center gap-3 bg-white border border-slate-200 rounded-xl px-4 py-2"><span className="relative w-9 h-9 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center font-bold overflow-hidden">{account?.iconDataUrl?<Image src={account.iconDataUrl} alt="" fill unoptimized className="object-cover"/>:account?.name.slice(0,1)}</span><div><b className="text-sm text-[#172033]">{account?.name||'読み込み中'}</b><p className="text-[11px] text-slate-500">{account?.jobTitle}・{account?.status}</p></div></div></header>
  <div className="flex flex-wrap gap-2 text-xs"><span className="bg-emerald-50 text-emerald-700 border border-emerald-200 rounded-full px-3 py-1.5">登録企業限定</span><span className="bg-blue-50 text-blue-700 border border-blue-200 rounded-full px-3 py-1.5">登録企業 {members.length}社</span><span className="bg-white text-slate-600 border border-slate-200 rounded-full px-3 py-1.5">未登録企業への送信はAPIで拒否</span></div>
  <div className="grid grid-cols-1 xl:grid-cols-[300px_1fr] gap-5 items-start">
   <section className="bg-white border border-slate-200 rounded-xl overflow-hidden xl:sticky xl:top-0"><div className="px-4 py-4 border-b border-slate-200"><div className="flex items-center justify-between"><h3 className="font-bold text-[#172033]">トーク</h3><span className="text-xs text-slate-400">最新順</span></div><p className="text-xs text-slate-500 mt-1">登録企業との会話</p></div><div className="divide-y divide-slate-100 max-h-[610px] overflow-auto">{talks.length===0?<div className="p-8 text-center text-xs text-slate-400"><p>トークはまだありません</p><p className="mt-2">公開課題から企業へDMすると、ここに表示されます。</p></div>:talks.map(({member,latest})=><button key={member.companyId} onClick={()=>selectCompany(member.companyId)} className={`w-full text-left px-4 py-3.5 transition ${target===member.companyId?'bg-blue-50':'hover:bg-slate-50'}`}><div className="flex gap-3"><span className="w-10 h-10 shrink-0 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center font-bold">{member.companyName.slice(0,1)}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><b className="text-sm text-[#172033] truncate">{member.companyName}</b><span className="text-[10px] text-slate-400 shrink-0">{new Date(latest!.createdAt).toLocaleDateString('ja-JP',{month:'numeric',day:'numeric'})}</span></div><p className="text-xs text-slate-500 truncate mt-1">{latest!.senderCompanyId===myCompany?'自分: ':''}{latest!.body}</p></div></div></button>)}</div></section>
   <section className="bg-white border border-slate-200 rounded-xl overflow-hidden xl:col-span-2 xl:row-start-2"><div className="p-5 border-b border-slate-200"><h3 className="font-bold text-[#172033]">登録企業の公開課題を探す</h3><div className="flex gap-2 mt-3"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load(query)}} placeholder="課題・業界・地域・企業名で検索" className={`${field} flex-1`}/><button onClick={()=>void load(query)} className="bg-blue-600 hover:bg-blue-500 text-white rounded-lg px-5 font-bold text-sm">検索</button></div></div>
    <div className="divide-y divide-slate-100 max-h-[650px] overflow-auto">{loading?<p className="p-12 text-center text-slate-400">検索中...</p>:challenges.length===0?<p className="p-12 text-center text-slate-400">登録企業の公開課題に一致する結果がありません</p>:challenges.map(c=><article key={c.id} className="p-5 hover:bg-slate-50"><div className="flex justify-between gap-3"><div><div className="flex gap-2 items-center"><b className="text-sm text-[#172033]">{c.companyName}</b><span className="text-[11px] text-slate-500">{c.industryName}・{c.prefecture}</span></div><h4 className="font-bold text-blue-700 mt-2">{c.title}</h4></div><span className={`h-fit text-xs rounded-full px-2.5 py-1 ${c.urgency==='高'?'bg-red-50 text-red-600':'bg-amber-50 text-amber-700'}`}>緊急度 {c.urgency}</span></div><p className="text-sm text-slate-600 mt-2 leading-6">{c.detail||'詳細はDMでお問い合わせください。'}</p><div className="flex justify-between items-center mt-3"><span className="text-xs bg-slate-100 text-slate-600 rounded px-2 py-1">{c.category}</span><button disabled={c.companyId===myCompany} onClick={()=>selectCompany(c.companyId)} className="bg-emerald-600 hover:bg-emerald-500 disabled:bg-slate-200 disabled:text-slate-400 text-white rounded-lg px-4 py-2 text-xs font-bold">{c.companyId===myCompany?'自社の課題':'この企業へDM'}</button></div></article>)}</div>
   </section>
   <section className="bg-white border border-slate-200 rounded-xl overflow-hidden xl:col-start-2 xl:row-start-1"><div className="p-4 border-b border-slate-200"><h3 className="font-bold text-[#172033]">企業間DM</h3><p className="text-xs text-slate-500 mt-1">送受信双方が登録企業の場合のみ利用できます。</p><select value={target} onChange={e=>selectCompany(e.target.value)} className={`${field} w-full mt-3`}><option value="">やり取りする企業を選択</option>{members.filter(m=>m.companyId!==myCompany).map(m=><option key={m.companyId} value={m.companyId}>{m.companyName}</option>)}</select></div>
    {targetMember?<><div className="px-4 py-3 bg-blue-50 border-b border-blue-100"><b className="text-sm text-blue-800">{targetMember.companyName}</b><p className="text-xs text-blue-600 mt-1">{targetMember.industryName}・{targetMember.prefecture}</p></div><div className="h-80 overflow-auto p-4 space-y-3 bg-slate-50">{conversation.length===0&&<p className="text-center text-xs text-slate-400 mt-24">最初のDMを送り、課題について提案・相談しましょう。</p>}{conversation.map(m=><div key={m.id} className={`flex ${m.senderCompanyId===myCompany?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm ${m.senderCompanyId===myCompany?'bg-blue-600 text-white rounded-br-sm':'bg-white border border-slate-200 text-slate-700 rounded-bl-sm'}`}><p className="whitespace-pre-wrap">{m.body}</p><span className={`block text-[10px] mt-1 ${m.senderCompanyId===myCompany?'text-blue-100':'text-slate-400'}`}>{new Date(m.createdAt).toLocaleString('ja-JP')}</span></div></div>)}</div><div className="p-4 border-t border-slate-200"><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={4} placeholder="課題への提案や相談内容を入力" className="w-full border border-slate-300 rounded-lg p-3 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"/><button onClick={()=>void send()} className="w-full mt-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg py-2.5 text-sm font-bold">登録企業へDMを送信</button></div></>:<div className="h-[500px] flex items-center justify-center text-center text-sm text-slate-400 px-8">公開課題の「この企業へDM」または送信先一覧から、登録企業を選択してください。</div>}
   </section>
  </div>
 </div>
}
