'use client';

import { useCallback, useEffect, useState } from 'react';

type Company={id:string;companyName:string};
type User={id:string;name:string;role:string};
type Task={id:string;title:string;description:string;companyId:string|null;companyName:string|null;assigneeId:string|null;assigneeName:string|null;status:string;priority:string;dueDate:string};
type Permission={userId:string;userName:string;companyId:string;companyName:string;accessLevel:string};
type Challenge={id:string;companyId:string;companyName:string;title:string;detail:string;category:string;urgency:string;source:string;contactIntent:string};

const input='w-full h-10 bg-white border border-slate-300 rounded-lg px-3 text-sm text-[#172033] focus:outline-none focus:ring-2 focus:ring-blue-500';

export default function WorkspacePanel({companies}:{companies:Company[]}) {
  const [users,setUsers]=useState<User[]>([]),[tasks,setTasks]=useState<Task[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[challenges,setChallenges]=useState<Challenge[]>([]);
  const [currentUser,setCurrentUser]=useState('user-admin'),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
  const [task,setTask]=useState({title:'',description:'',companyId:'',assigneeId:'',priority:'中',dueDate:''});
  const [permission,setPermission]=useState({userId:'user-sato',companyId:'',accessLevel:'閲覧'});
  const [challenge,setChallenge]=useState({companyId:'',title:'',detail:'',category:'業務効率化',urgency:'中',source:'ヒアリング',contactIntent:'営業提案を受付中'});
  const toast=(message:string)=>{setNotice(message);setTimeout(()=>setNotice(''),3000)};
  const load=useCallback(async(userId=currentUser)=>{setLoading(true);try{const r=await fetch(`/api/workspace?userId=${encodeURIComponent(userId)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error();setUsers(d.users??[]);setTasks(d.tasks??[]);setPermissions(d.permissions??[]);setChallenges(d.challenges??[])}catch{toast('データを読み込めませんでした')}finally{setLoading(false)}},[currentUser]);
  // 初回にサーバー保存済みの業務データを同期する。
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  const create=async(resource:string,values:object)=>{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource,...values})}),d=await r.json();if(!r.ok)return toast(d.error||'登録できませんでした');await load();toast('登録しました')};
  const updateTask=async(item:Task,changes:Partial<Task>)=>{const r=await fetch('/api/workspace',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:'task',...item,...changes})});if(r.ok)await load();else toast('更新できませんでした')};
  const remove=async(resource:string,item:{id?:string;userId?:string;companyId?:string|null})=>{const q=new URLSearchParams({resource,id:item.id??'',userId:item.userId??'',companyId:item.companyId??''});if((await fetch(`/api/workspace?${q}`,{method:'DELETE'})).ok){await load();toast('削除しました')}};

  return <div className="space-y-6 pb-12">
    {notice&&<div className="fixed top-5 right-5 z-50 bg-emerald-600 text-white rounded-lg px-4 py-3 text-sm shadow-xl">{notice}</div>}
    <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><h2 className="text-2xl font-bold text-[#161c2c]">チーム・課題管理</h2><p className="text-sm text-slate-500 mt-1">営業タスク、送信担当、取引先権限、営業受付企業の課題を一元管理します。</p></div><label className="text-xs font-semibold text-slate-500">表示ユーザー<select value={currentUser} onChange={e=>{setCurrentUser(e.target.value);void load(e.target.value)}} className="ml-2 h-10 bg-white border border-slate-300 rounded-lg px-3 text-sm text-[#172033]">{users.map(u=><option key={u.id} value={u.id}>{u.name}（{u.role}）</option>)}</select></label></header>
    {loading?<div className="bg-white border border-slate-200 rounded-xl py-20 text-center text-slate-500">読み込み中...</div>:<>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['未完了タスク',tasks.filter(t=>t.status!=='完了').length],['担当者',users.length],['権限設定',permissions.length],['登録課題',challenges.length]].map(([label,value])=><div key={String(label)} className="bg-white border border-slate-200 rounded-xl p-4"><b className="text-2xl text-blue-600">{value}</b><div className="text-xs text-slate-500 mt-1">{label}</div></div>)}</div>
      <section className="bg-white border border-slate-200 rounded-xl p-5 space-y-4"><div><h3 className="font-bold text-[#172033]">タスク管理・送信担当割り当て</h3><p className="text-xs text-slate-500 mt-1">メール・DM送信やフォロー業務を担当者へ割り当てます。</p></div><div className="grid grid-cols-1 md:grid-cols-6 gap-2"><input value={task.title} onChange={e=>setTask(v=>({...v,title:e.target.value}))} placeholder="タスク名 *" className={`${input} md:col-span-2`}/><select value={task.companyId} onChange={e=>setTask(v=>({...v,companyId:e.target.value}))} className={input}><option value="">取引先なし</option>{companies.map(c=><option key={c.id} value={c.id}>{c.companyName}</option>)}</select><select value={task.assigneeId} onChange={e=>setTask(v=>({...v,assigneeId:e.target.value}))} className={input}><option value="">担当者を選択</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><input type="date" value={task.dueDate} onChange={e=>setTask(v=>({...v,dueDate:e.target.value}))} className={input}/><button onClick={()=>{if(!task.title.trim())return toast('タスク名を入力してください');void create('task',task);setTask({title:'',description:'',companyId:'',assigneeId:'',priority:'中',dueDate:''})}} className="h-10 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-sm font-bold">追加</button></div><div className="space-y-2">{tasks.length===0&&<p className="py-8 text-center text-sm text-slate-400">表示できるタスクはありません</p>}{tasks.map(t=><article key={t.id} className="grid grid-cols-1 md:grid-cols-[1fr_150px_120px_90px_30px] gap-2 items-center bg-slate-50 border border-slate-200 rounded-lg p-3"><div><b className="text-sm text-[#172033]">{t.title}</b><p className="text-xs text-slate-500 mt-1">{t.companyName||'社内タスク'} ・ 期限 {t.dueDate||'未設定'}</p></div><select value={t.assigneeId??''} onChange={e=>void updateTask(t,{assigneeId:e.target.value})} className={input}><option value="">未割当</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select value={t.status} onChange={e=>void updateTask(t,{status:e.target.value})} className={input}>{['未着手','進行中','確認待ち','完了'].map(v=><option key={v}>{v}</option>)}</select><select value={t.priority} onChange={e=>void updateTask(t,{priority:e.target.value})} className={input}>{['低','中','高'].map(v=><option key={v}>{v}</option>)}</select><button onClick={()=>void remove('task',t)} className="text-red-500 text-xl">×</button></article>)}</div></section>
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-5 items-start">
        <section className="bg-white border border-slate-200 rounded-xl p-5 space-y-4"><div><h3 className="font-bold text-[#172033]">特定取引先への権限</h3><p className="text-xs text-slate-500 mt-1">ユーザーごとに閲覧・編集・管理権限を設定します。</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><select value={permission.userId} onChange={e=>setPermission(v=>({...v,userId:e.target.value}))} className={input}>{users.filter(u=>u.role!=='管理者').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select value={permission.companyId} onChange={e=>setPermission(v=>({...v,companyId:e.target.value}))} className={input}><option value="">取引先を選択 *</option>{companies.map(c=><option key={c.id} value={c.id}>{c.companyName}</option>)}</select><select value={permission.accessLevel} onChange={e=>setPermission(v=>({...v,accessLevel:e.target.value}))} className={input}>{['閲覧','編集','管理'].map(v=><option key={v}>{v}</option>)}</select><button onClick={()=>void create('permission',permission)} className="h-10 bg-amber-500 hover:bg-amber-400 text-white rounded-lg text-sm font-bold">権限を保存</button></div><div className="max-h-72 overflow-auto space-y-2">{permissions.map(p=><div key={`${p.userId}-${p.companyId}`} className="flex justify-between items-center bg-slate-50 border border-slate-200 rounded-lg p-3 text-sm"><div><b>{p.userName}</b><span className="block text-xs text-slate-500 mt-1">{p.companyName}</span></div><div className="flex gap-3"><span className="text-amber-600 font-bold">{p.accessLevel}</span><button onClick={()=>void remove('permission',p)} className="text-red-500">×</button></div></div>)}</div></section>
        <section className="bg-white border border-slate-200 rounded-xl p-5 space-y-3"><div><h3 className="font-bold text-[#172033]">営業受付企業の課題データベース</h3><p className="text-xs text-slate-500 mt-1">営業提案を受けたい企業の課題と緊急度を登録します。</p></div><select value={challenge.companyId} onChange={e=>setChallenge(v=>({...v,companyId:e.target.value}))} className={input}><option value="">会社を選択 *</option>{companies.map(c=><option key={c.id} value={c.id}>{c.companyName}</option>)}</select><input value={challenge.title} onChange={e=>setChallenge(v=>({...v,title:e.target.value}))} placeholder="課題名 *" className={input}/><textarea value={challenge.detail} onChange={e=>setChallenge(v=>({...v,detail:e.target.value}))} rows={3} placeholder="課題の詳細・希望する提案内容" className={`${input} h-auto py-2`}/><div className="grid grid-cols-3 gap-2"><input value={challenge.category} onChange={e=>setChallenge(v=>({...v,category:e.target.value}))} className={input}/><select value={challenge.urgency} onChange={e=>setChallenge(v=>({...v,urgency:e.target.value}))} className={input}>{['低','中','高'].map(v=><option key={v}>{v}</option>)}</select><button onClick={()=>void create('challenge',challenge)} className="bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-sm font-bold">課題を登録</button></div><div className="max-h-72 overflow-auto space-y-2">{challenges.map(c=><article key={c.id} className="bg-slate-50 border border-slate-200 rounded-lg p-3"><div className="flex justify-between"><div><b className="text-xs text-emerald-700">{c.companyName}</b><h4 className="text-sm font-bold mt-1">{c.title}</h4></div><button onClick={()=>void remove('challenge',c)} className="text-red-500">×</button></div><p className="text-xs text-slate-500 mt-2">{c.detail||'詳細なし'}</p><div className="flex gap-2 mt-2 text-[11px]"><span>{c.category}</span><span className="text-red-600">緊急度 {c.urgency}</span><span className="text-emerald-700">{c.contactIntent}</span></div></article>)}</div></section>
      </div>
    </>}
  </div>;
}
