'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
type Member={companyId:string;companyName:string};
type Subscription={companyId:string;companyName:string;status:string;trialStart:string;trialEnd:string;ticketsRemaining:number;contractedAt:string|null;billingStart:string|null;discountMonthlyYen:number;discountMonthsRemaining:number};
const yen=(v:number)=>`${v.toLocaleString('ja-JP')}円`;
const date=(v:string|null)=>v?new Date(v).toLocaleDateString('ja-JP'):'—';
export default function BillingPanel(){
 const [members,setMembers]=useState<Member[]>([]),[subscriptions,setSubscriptions]=useState<Subscription[]>([]),[companyId,setCompanyId]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [n,b]=await Promise.all([fetch('/api/network',{cache:'no-store'}).then(r=>r.json()),fetch(`/api/billing?companyId=${encodeURIComponent(companyId)}`,{cache:'no-store'}).then(r=>r.json())]);setMembers(n.members??[]);setSubscriptions(b.subscriptions??[]);if(!companyId&&n.members?.[0]){setCompanyId(n.members[0].companyId);window.localStorage.setItem('eigyo-navi-company-id',n.members[0].companyId)}},[companyId]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);
 const current=useMemo(()=>subscriptions.find(s=>s.companyId===companyId),[subscriptions,companyId]);
 const act=async(action:string)=>{setBusy(true);const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,companyId,amount:1})}),d=await r.json();setBusy(false);if(!r.ok){setNotice(d.error||'処理できませんでした');return}setNotice(action==='start-trial'?'3か月無料トライアルを開始しました':action==='contract'?'本契約を受け付けました。料金は翌月から発生します':'チケットを1枚使用しました');await load()};
 const statusLabel=current?.status==='trial'?'無料トライアル中':current?.status==='contracted_pending'?'本契約済み・課金開始待ち':current?.status==='active'?'本契約中':current?.status==='trial_expired'?'トライアル終了':'未開始';
 const discounted=current?Math.max(0,4000-current.discountMonthlyYen):4000;
 return <div className="space-y-6 pb-12"><header><span className="text-xs font-bold text-blue-600">PLAN & TICKETS</span><h2 className="text-2xl font-bold text-[#161c2c] mt-1">契約・無料トライアル管理</h2><p className="text-sm text-slate-500 mt-1">登録企業ごとに3か月無料、毎月100チケットを付与します。</p></header>{notice&&<div className="bg-blue-50 border border-blue-200 text-blue-700 rounded-lg px-4 py-3 text-sm">{notice}</div>}
 <div className="grid grid-cols-1 lg:grid-cols-[1fr_1.3fr] gap-5 items-start"><section className="bg-white border border-slate-200 rounded-xl p-5 space-y-4"><div><span className="text-xs font-semibold text-slate-500">ご契約企業</span><div className="mt-2 border border-slate-200 bg-slate-50 rounded-lg px-4 py-3 text-sm font-bold text-[#172033]">{members.find(m=>m.companyId===companyId)?.companyName||'企業情報を読み込み中'}</div></div><div className="rounded-xl bg-slate-50 border border-slate-200 p-4"><span className="text-xs text-slate-500">現在の状態</span><div className="text-lg font-bold text-blue-700 mt-1">{statusLabel}</div></div>{!current?<button disabled={busy||!companyId} onClick={()=>void act('start-trial')} className="w-full bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white rounded-lg py-3 font-bold">3か月無料トライアルを開始</button>:<><div className="grid grid-cols-2 gap-3"><div className="border border-slate-200 rounded-lg p-3"><span className="text-xs text-slate-500">終了予定日</span><b className="block mt-1">{date(current.trialEnd)}</b></div><div className="border border-slate-200 rounded-lg p-3"><span className="text-xs text-slate-500">今月の残り</span><b className="block mt-1 text-xl text-emerald-600">{current.ticketsRemaining}枚</b></div></div><p className="rounded-lg bg-blue-50 border border-blue-100 px-3 py-2 text-xs text-blue-700">AI検索・文章作成などの対象機能を利用すると、チケットが自動的に消費されます。</p>{current.status==='trial'&&<button disabled={busy} onClick={()=>void act('contract')} className="w-full bg-blue-600 hover:bg-blue-500 text-white rounded-lg py-3 font-bold">無料期間中に本契約する</button>}</>}</section>
 <section className="bg-white border border-slate-200 rounded-xl overflow-hidden"><div className="p-5 border-b border-slate-200"><h3 className="font-bold text-[#172033]">料金と早期契約特典</h3><p className="text-xs text-slate-500 mt-1">月額4,000円。本契約した月には請求せず、翌月から料金が発生します。</p></div><div className="p-5 space-y-4"><div className="grid grid-cols-3 gap-3">{[['無料期間','3か月'],['月間チケット','100枚'],['通常月額','4,000円']].map(([a,b])=><div key={a} className="bg-slate-50 border border-slate-200 rounded-lg p-3 text-center"><b className="text-lg text-blue-700">{b}</b><span className="block text-xs text-slate-500 mt-1">{a}</span></div>)}</div><div className="border-l-4 border-amber-400 bg-amber-50 rounded-r-lg p-4 text-sm text-amber-900"><b>無料期間中の本契約特典</b><p className="mt-1 leading-6">契約時点で残っている無料期間を金額換算し、その合計を本契約開始後6か月に均等配分して割引します。</p></div>{current?.contractedAt&&<div className="border border-blue-200 rounded-xl p-4 space-y-3"><h4 className="font-bold text-blue-800">この企業の契約内容</h4><div className="grid grid-cols-2 gap-y-3 text-sm"><span className="text-slate-500">申込日</span><b>{date(current.contractedAt)}</b><span className="text-slate-500">課金開始日</span><b>{date(current.billingStart)}</b><span className="text-slate-500">6か月間の月額割引</span><b className="text-emerald-700">−{yen(current.discountMonthlyYen)}</b><span className="text-slate-500">割引後月額</span><b>{yen(discounted)}</b></div></div>}<p className="text-[11px] text-slate-400 leading-5">割引額＝月額4,000円×3か月×契約時点の無料期間残存率÷6か月（1円単位で四捨五入）。チケットは各トライアル月の開始時に100枚へ更新され、未使用分は翌月へ繰り越しません。</p></div></section></div></div>
}
