'use client';
import { useEffect, useState } from 'react';

const companies = [
  { score:94, name:'東邦マテリアル株式会社', kana:'TOHO MATERIALS', place:'愛知県豊田市', people:'従業員 640名', signal:'新工場建設', date:'2時間前', tone:'red', revenue:480, units:12, probability:78, reasons:['新工場建設を発表','設備投資 35億円を決定','24時間稼働の生産ラインを新設'], proposal:'新工場の死角を減らすAI監視カメラと、夜間の異常検知を組み合わせた導入プランをご提案。', contact:'生産技術部 / 設備保全責任者' },
  { score:89, name:'北陸精機株式会社', kana:'HOKURIKU SEIKI', place:'石川県金沢市', people:'従業員 310名', signal:'設備投資拡大', date:'5時間前', tone:'orange', revenue:280, units:7, probability:71, reasons:['第2工場の設備更新を発表','省人化プロジェクトを開始','夜間稼働率を40%へ拡大'], proposal:'既存設備を止めずに増設できるワイヤレス監視と、遠隔確認ダッシュボードをご提案。', contact:'製造本部 / DX推進担当' },
  { score:86, name:'関東ロジスティクス株式会社', kana:'KANTO LOGISTICS', place:'埼玉県川越市', people:'従業員 890名', signal:'新拠点開設', date:'昨日', tone:'yellow', revenue:620, units:16, probability:68, reasons:['大型物流センターを新設','庫内作業の自動化を推進','2027年1月の稼働を予定'], proposal:'搬入口・保管エリアの一元監視と、侵入・滞留を自動通知する安全管理パッケージをご提案。', contact:'物流企画部 / センター長' },
  { score:82, name:'大和フーズ株式会社', kana:'YAMATO FOODS', place:'大阪府堺市', people:'従業員 470名', signal:'品質管理強化', date:'2日前', tone:'green', revenue:360, units:9, probability:64, reasons:['食品事故防止の新方針を公表','製造ラインを3本増設','衛生監査を四半期ごとに実施'], proposal:'録画確認を短縮する工程別検索と、衛生区域への入退室検知をご提案。', contact:'品質保証部 / 工場管理責任者' },
  { score:78, name:'西日本パーツ株式会社', kana:'WEST JAPAN PARTS', place:'広島県福山市', people:'従業員 225名', signal:'補助金採択', date:'3日前', tone:'blue', revenue:180, units:5, probability:58, reasons:['省力化投資補助金に採択','倉庫管理システムを刷新','設備予算 1.2億円を確保'], proposal:'補助金予算に合わせた段階導入と、倉庫・製造現場を横断する監視プランをご提案。', contact:'経営企画室 / 情報システム担当' },
];

export default function Home(){
 const [active,setActive]=useState(0), [query,setQuery]=useState('明日電話すべき会社を5社出してください'), [loading,setLoading]=useState(false), [toast,setToast]=useState(''), [productOpen,setProductOpen]=useState(false);
 const initialProduct={name:'工場向けAI監視カメラ',category:'セキュリティ・IoT',target:'製造業、物流業、食品工場',features:'AIによる異常検知、24時間遠隔監視、既存設備への後付け対応',problems:'工場内の事故防止、夜間の省人化、設備異常の早期発見'};
 const [product,setProduct]=useState(initialProduct); const company=companies[active];
 useEffect(()=>{const saved=localStorage.getItem('eigyo-navi-product');if(saved)setProduct({...initialProduct,...JSON.parse(saved)})},[]);
 const saveProduct=()=>{localStorage.setItem('eigyo-navi-product',JSON.stringify(product));setProductOpen(false);setToast('自社製品を登録しました。営業先ごとのAI予測に反映されます');setTimeout(()=>setToast(''),3200)};
 const analyze=()=>{setLoading(true);setTimeout(()=>{setLoading(false);setActive(0);setToast('1,284社から有望企業を抽出しました');setTimeout(()=>setToast(''),2600)},900)};
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><span>S</span><b>営業ナビ</b></div><nav>{[['⌂','ホーム'],['◎','有望企業'],['⌕','企業検索'],['▤','アプローチリスト']].map((n,i)=><button key={n[1]} className={i===0?'active':''}><i>{n[0]}</i>{n[1]}</button>)}<p>管理</p>{[['⌁','自社サービス'],['♙','チーム'],['⚙','設定']].map(n=><button key={n[1]} onClick={()=>n[1]==='自社サービス'&&setProductOpen(true)}><i>{n[0]}</i>{n[1]}</button>)}</nav><div className="plan"><em>PRO PLAN</em><b>分析枠 72%</b><span><i/></span><small>3,600 / 5,000社</small></div><div className="user"><span>YK</span><div><b>山田 健太</b><small>営業部 マネージャー</small></div><strong>⋮</strong></div></aside>
  <section className="workspace"><header><div><h1>おはようございます、山田さん</h1><p>今日の営業チャンスをAIが見つけました。</p></div><div className="actions"><button>♧<i/></button><button onClick={()=>setProductOpen(true)}>＋ 自社サービスを編集</button></div></header>
   <div className="ask"><div className="orb">✦</div><div className="askcopy"><b>AI営業アシスタント</b><small>何をお探しですか？</small></div><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&analyze()} aria-label="AIへの依頼"/><button onClick={analyze} disabled={loading}>{loading?'…':'→'}</button></div><div className="chips"><small>例：</small><button onClick={()=>setQuery('今週、設備投資を発表した企業')}>今週、設備投資を発表した企業</button><button onClick={()=>setQuery('関東の製造業で採用を強化中')}>関東の製造業で採用を強化中</button></div></div>
   <div className="stats">{[['✦','本日の新着チャンス','12社','前日比 +4社','purple'],['↗','高優先度企業','28社','スコア 80以上','green'],['◷','今週のアプローチ','7件','目標まであと3件','orange']].map(s=><div key={s[1]}><span className={s[4]}>{s[0]}</span><p>{s[1]}<b>{s[2]}</b><small>{s[3]}</small></p></div>)}</div>
   <div className="sectionhead"><div><h2>明日、電話すべき会社</h2><p>AIが公開情報を分析し、受注確度の高い順に並べています</p></div><button onClick={analyze}>↻ 最新情報に更新</button></div>
   <div className="grid"><div className="list">{companies.map((c,i)=><button key={c.name} className={`company ${active===i?'selected':''}`} onClick={()=>setActive(i)}><span className={`score ${c.tone}`}><b>{c.score}</b><small>/100</small></span><span className="companymain"><small>{c.kana}</small><b>{c.name}</b><em>⌖ {c.place}　·　{c.people}</em></span><span className="signal"><b className={c.tone}>● {c.signal}</b><small>{c.date}</small></span><strong>›</strong></button>)}</div>
    <aside className="detail"><div className="detailtop"><span className={`bigscore ${company.tone}`}><b>{company.score}</b><small>/100</small></span><div><small>{company.kana}</small><h3>{company.name}</h3><p>⌖ {company.place}　·　{company.people}</p></div><button>×</button></div><section><h4><span>✦</span> AIが注目した理由</h4><ul>{company.reasons.map((r,i)=><li key={r}><i>{i+1}</i><span>{r}<small>{['プレスリリース','ニュース','企業サイト'][i]}</small></span></li>)}</ul></section><div className="forecast prospectforecast"><div className="forecasthead"><span>✦ この営業先のAI受注予測</span><small>企業規模・投資情報・類似商談から算出</small></div><div className="forecastgrid"><div><small>予想収益</small><strong>{company.revenue.toLocaleString()}<b>万円</b></strong></div><div><small>予想販売数</small><strong>{company.units}<b>台</b></strong></div><em>受注確度 {company.probability}%</em></div></div><div className="proposal"><h4>提案すべき内容</h4><p>{company.proposal}</p><div><span>推奨アプローチ先</span><b>{company.contact}</b></div></div><div className="talk"><div><h4>電話トーク例</h4><button onClick={()=>{navigator.clipboard?.writeText(company.proposal);setToast('トーク例をコピーしました')}}>コピー</button></div><p>「新しい取り組みに関する発表を拝見し、お電話しました。弊社では製造現場向けに、<mark>{company.proposal.slice(0,31)}</mark>…」</p></div><div className="detailactions"><button onClick={()=>setToast('アプローチリストに追加しました')}>＋ リストに追加</button><button onClick={()=>setToast('担当者候補を検索しています')}>担当者を探す →</button></div></aside>
   </div>
  </section>{productOpen&&<div className="modalback" onMouseDown={e=>e.target===e.currentTarget&&setProductOpen(false)}><section className="productmodal" role="dialog" aria-modal="true" aria-labelledby="product-title"><header><div><span>✦</span><div><h2 id="product-title">自社製品を登録</h2><p>AIが営業チャンスを探すための基準になります</p></div></div><button onClick={()=>setProductOpen(false)} aria-label="閉じる">×</button></header><div className="formbody"><label><span>製品・サービス名 <b>必須</b></span><input value={product.name} onChange={e=>setProduct({...product,name:e.target.value})} placeholder="例：工場向けAI監視カメラ"/></label><div className="twocol"><label><span>製品カテゴリ</span><select value={product.category} onChange={e=>setProduct({...product,category:e.target.value})}><option>セキュリティ・IoT</option><option>業務システム・SaaS</option><option>製造設備・機械</option><option>人材・採用</option><option>マーケティング</option><option>コンサルティング</option><option>その他</option></select></label><label><span>ターゲット業種</span><select value={product.target} onChange={e=>setProduct({...product,target:e.target.value})}><option value="製造業、物流業、食品工場">製造・物流・食品工場</option><option value="製造業">製造業</option><option value="物流・倉庫業">物流・倉庫業</option><option value="食品・飲料製造業">食品・飲料製造業</option><option value="建設・不動産業">建設・不動産業</option><option value="小売・卸売業">小売・卸売業</option><option value="医療・介護">医療・介護</option><option value="IT・通信業">IT・通信業</option><option value="金融・保険業">金融・保険業</option><option value="その他">その他</option></select></label></div><label><span>製品の特徴・強み <b>必須</b></span><textarea value={product.features} onChange={e=>setProduct({...product,features:e.target.value})} rows={3}/><small>具体的な機能や競合との違いを書くと、マッチング精度が上がります</small></label><label><span>解決できる課題</span><textarea value={product.problems} onChange={e=>setProduct({...product,problems:e.target.value})} rows={3}/></label><div className="aihint"><span>✦</span><p><b>AI分析への反映</b>登録内容をもとに、ニュース・採用・設備投資などの公開情報から「今ニーズがありそうな企業」を毎日探します。</p></div></div><footer><button onClick={()=>setProductOpen(false)}>キャンセル</button><button onClick={saveProduct} disabled={!product.name.trim()||!product.features.trim()}>登録して分析に反映 →</button></footer></section></div>}{toast&&<div className="toast">✓ {toast}</div>}
 </main>
}
