import {DatabaseSync} from 'node:sqlite';
import {join} from 'node:path';
import {NextResponse} from 'next/server';
import {sessionAccountId} from '@/app/lib/session';
const dbPath=join(process.env.DATA_DIR??join(process.cwd(),'data'),'companies.sqlite');
const clean=(v:unknown,n=200)=>String(v??'').trim().slice(0,n);
function openDb(){const db=new DatabaseSync(dbPath);db.exec(`CREATE UNIQUE INDEX IF NOT EXISTS companies_id_unique ON companies(id);
 CREATE TABLE IF NOT EXISTS network_members(companyId TEXT PRIMARY KEY,offerSummary TEXT NOT NULL DEFAULT '',profile TEXT NOT NULL DEFAULT '',joinedAt TEXT NOT NULL,lastActiveAt TEXT NOT NULL,FOREIGN KEY(companyId) REFERENCES companies(id) ON DELETE CASCADE);
 CREATE TABLE IF NOT EXISTS member_accounts(id TEXT PRIMARY KEY,companyId TEXT NOT NULL,name TEXT NOT NULL,jobTitle TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT '対応可能',internalEmail TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',iconDataUrl TEXT NOT NULL DEFAULT '',createdAt TEXT NOT NULL,updatedAt TEXT NOT NULL,FOREIGN KEY(companyId) REFERENCES companies(id) ON DELETE CASCADE);`);
 const registered=(db.prepare('SELECT COUNT(*) count FROM network_members').get() as {count:number}).count;if(!registered){const now=new Date().toISOString(),rows=db.prepare('SELECT id,businessDescription FROM companies ORDER BY salesScore DESC LIMIT 20').all() as Array<{id:string;businessDescription:string}>,add=db.prepare('INSERT OR IGNORE INTO network_members VALUES(?,?,?,?,?)');rows.forEach(c=>add.run(c.id,c.businessDescription,c.businessDescription,now,now))}
 const companies=db.prepare('SELECT companyId FROM network_members ORDER BY companyId LIMIT 3').all() as Array<{companyId:string}>;const now=new Date().toISOString(),seed=db.prepare('INSERT OR IGNORE INTO member_accounts VALUES(?,?,?,?,?,?,?,?,?,?)');companies.forEach((c,i)=>seed.run(`account-demo-${i+1}`,c.companyId,['山田 太郎','佐藤 花子','鈴木 健'][i],['営業部長','営業担当','事業開発担当'][i],i===2?'離席中':'対応可能',`member${i+1}@example.jp`,`03-0000-000${i+1}`,'',now,now));return db}
export async function GET(){const id=await sessionAccountId();if(!id)return NextResponse.json({error:'ログインが必要です'},{status:401});const db=openDb();try{const account=db.prepare(`SELECT a.*,c.companyName FROM member_accounts a JOIN companies c ON c.id=a.companyId WHERE a.id=?`).get(id);if(!account)return NextResponse.json({error:'アカウントが見つかりません'},{status:404});return NextResponse.json({account})}finally{db.close()}}
export async function PATCH(request:Request){const id=await sessionAccountId();if(!id)return NextResponse.json({error:'ログインが必要です'},{status:401});const b=await request.json(),name=clean(b.name,100),email=clean(b.internalEmail,200),phone=clean(b.phone,30),icon=clean(b.iconDataUrl,700000),db=openDb();try{if(!name)return NextResponse.json({error:'名前が必要です'},{status:400});if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return NextResponse.json({error:'メールアドレスの形式を確認してください'},{status:400});if(icon&&!/^data:image\/(png|jpeg|webp);base64,/.test(icon))return NextResponse.json({error:'アイコンはPNG・JPEG・WebPにしてください'},{status:400});const result=db.prepare('UPDATE member_accounts SET name=?,jobTitle=?,status=?,internalEmail=?,phone=?,iconDataUrl=?,updatedAt=? WHERE id=?').run(name,clean(b.jobTitle,100),clean(b.status,50)||'対応可能',email,phone,icon,new Date().toISOString(),id);if(!result.changes)return NextResponse.json({error:'アカウントが見つかりません'},{status:404});return NextResponse.json({ok:true})}finally{db.close()}}
