import {NextResponse} from 'next/server';
import {DatabaseSync} from 'node:sqlite';
import {join} from 'node:path';
import {cookies} from 'next/headers';
import {SESSION_COOKIE,sessionAccountId} from '@/app/lib/session';
const dbPath=join(process.env.DATA_DIR??join(process.cwd(),'data'),'companies.sqlite');
function openDb(){const db=new DatabaseSync(dbPath);db.exec('CREATE TABLE IF NOT EXISTS account_sessions(token TEXT PRIMARY KEY,accountId TEXT NOT NULL,createdAt TEXT NOT NULL,expiresAt TEXT NOT NULL)');return db}
function setSession(response:NextResponse,request:Request,accountId:string,db:DatabaseSync){const token=crypto.randomUUID(),now=new Date(),expires=new Date(now.getTime()+30*86400000);db.prepare('INSERT INTO account_sessions VALUES(?,?,?,?)').run(token,accountId,now.toISOString(),expires.toISOString());response.cookies.set(SESSION_COOKIE,token,{httpOnly:true,sameSite:'strict',secure:new URL(request.url).protocol==='https:',path:'/',maxAge:60*60*24*30})}
export async function GET(request:Request){let current=await sessionAccountId();const db=openDb();try{const table=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='member_accounts'").get();const accounts=table?db.prepare(`SELECT a.id,a.name,a.jobTitle,a.status,c.companyName FROM member_accounts a JOIN companies c ON c.id=a.companyId WHERE a.id NOT LIKE 'account-inbox-%' ORDER BY c.companyName,a.name`).all():[];if(!current)current=(accounts[0] as {id:string}|undefined)?.id??'account-demo-1';const response=NextResponse.json({ok:true,accountId:current,accounts});if(!(await sessionAccountId()))setSession(response,request,current,db);return response}finally{db.close()}}
export async function POST(request:Request){const body=await request.json(),accountId=String(body.accountId??'').trim(),db=openDb();try{const table=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='member_accounts'").get();if(!table||!db.prepare('SELECT id FROM member_accounts WHERE id=?').get(accountId))return NextResponse.json({error:'アカウントが見つかりません'},{status:404});const oldToken=(await cookies()).get(SESSION_COOKIE)?.value;if(oldToken)db.prepare('DELETE FROM account_sessions WHERE token=?').run(oldToken);const response=NextResponse.json({ok:true,accountId});setSession(response,request,accountId,db);return response}finally{db.close()}}
